[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8000
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-local-install-core" 