[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.9.2"

[build.processing]
  skip_processing = true
