[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[dev]
  framework = "#static"
  command = "npm start"
  targetPort = 3000
  port = 3000
  publish = "public"
  autoLaunch = true

[[plugins]]
package = "@netlify/plugin-local-install-core" 