[build]
  command = "mkdir -p functions/content/posts && cp content/posts/* functions/content/posts/ || true && ls -la functions/content/posts/ && npm install --legacy-peer-deps"
  publish = "public"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.20.8"
  NPM_FLAGS = "--no-optional"

[build.processing]
  skip_processing = true

[functions]
  directory = "functions"
