[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipInstall = true
    skipBuild = false
