[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[plugins]]
  package = "@netlify/plugin-nextjs"
