[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/content/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#static"
  staticServerPort = 3000

[[plugins]]
  package = "@netlify/plugin-local-install-core" 