[build]
  command = "mkdir -p functions/content/posts public/content/posts && cp -r content/posts/* functions/content/posts/ || true && cp -r content/posts/* public/content/posts/ || true && npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.8"

[functions]
  directory = "functions"
