[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
