[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 3000
  publish = "public"
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-local-install-core" 