[build]
  command = "echo 'Installing dependencies...' && npm install && echo 'Creating directories...' && mkdir -p functions/content/posts public/content/posts && echo 'Copying posts...' && cp -r content/posts/* functions/content/posts/ || echo 'No posts to copy to functions' && cp -r content/posts/* public/content/posts/ || echo 'No posts to copy to public' && echo 'Verifying posts...' && ls -la functions/content/posts/ && ls -la public/content/posts/"
  publish = "public"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.20.8"
  NPM_FLAGS = "--no-optional"

[build.processing]
  skip_processing = true

[functions]
  directory = "functions"
