[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    nextjsBasePath = ""

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[deploy]
  concurrency = 1
  max_concurrent_builds = 1

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["content/posts/**"]

[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"
