[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/content/*"
  to = "/.netlify/functions/content/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8000
  framework = "#custom"

[[plugins]]
  package = "@netlify/plugin-local-install-core" 