[build]
  publish = "public"
  command = """
    echo "Creating directories..."
    mkdir -p functions/content/posts public/content/posts
    echo "Copying posts..."
    cp -r content/posts/* functions/content/posts/ || echo "No posts to copy to functions"
    cp -r content/posts/* public/content/posts/ || echo "No posts to copy to public"
    echo "Verifying posts..."
    ls -la functions/content/posts/
    ls -la public/content/posts/
    echo "Installing dependencies..."
    npm install --legacy-peer-deps
  """
  functions = "functions"

[[redirects]]
  from = "/content/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 3000
  publish = "public"
  autoLaunch = true
  framework = "#static"

[[plugins]]
  package = "@netlify/plugin-local-install-core" 