[build]
  publish = "public"
  command = """
    echo "Installing dependencies..."
    npm install
    echo "Creating directories..."
    mkdir -p functions/content/posts public/content/posts
    echo "Copying posts..."
    cp -r content/posts/* functions/content/posts/ || echo "No posts to copy to functions"
    cp -r content/posts/* public/content/posts/ || echo "No posts to copy to public"
    echo "Copying entire content directory..."
    cp -r content functions/ || echo "No content directory to copy"
    echo "Verifying directories and files..."
    echo "Functions content:"
    ls -la functions/content/posts/
    echo "Public content:"
    ls -la public/content/posts/
    echo "Functions root content:"
    ls -la functions/content/
  """
  functions = "functions"

[[redirects]]
  from = "/content/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["content/posts/*"]

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 3000
  publish = "public"
  autoLaunch = true
  framework = "#static" 